spring:
  application:
    name: taskflow

  datasource:
    url: jdbc:postgresql://localhost:5433/taskflow
    username: postgres
    password: zaq1@WSX
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:ToJestBardzoDlugiTajnyKluczDoGenerowaniaTokenowJWT12345!}
    expiration: 86400000